### PR TITLE
JSON::Any -> JSON::MaybeXS

### PR DESCRIPTION
**Pull request by karenetheridge**
comments please - is this likely to cause any issue?
If not, I can pester t0m for comaint and shepherd it to cpan.

### CODE REVIEW

**Comment by frioux** [comment]
I know that @vanstyn had some weird reason for using JSON::DWIM or JSON::DWIW, can't recall which.

@vanstyn Was it in ::View::JSON and if so, what was the use case again?

**Comment by vanstyn** [comment]
@frioux - I used JSON::DWIW in Schema::Diff (https://github.com/vanstyn/DBIx-Class-Schema-Diff/commit/4f4a75d1e059a101f23bf13b164399df9b16c560) because I was tired of fighting with the standard JSON API and I was feeling lazy. That was for a new project though; I'm not sure if it relates to this case

**Comment by frioux** [comment]
Gotcha, just wasn't sure of the details, thanks!

**Comment by karenetheridge** [comment]
I've force-pushed a fix to t/01-server.t to remove the explicit use of JSON.pm. This fixes https://rt.cpan.org/Ticket/Display.html?id=34042 and also closes https://github.com/shadowcat-mst/catalyst-view-json/pull/2.

**Pull request merged**
